[workspace]
members = [
    "vqueue",
    "vsmtp",
    "vsmtp-common",
    "vsmtp-config",
    "vsmtp-delivery",
    "vsmtp-mail-parser",
    "vsmtp-rule-engine",
    "vsmtp-server",
    "vsmtp-test",
]
