[package]
edition = "2021"

name = "vsmtp"
version = "0.8.3"
license = "GPLv3"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vSMTP : the next-gen MTA. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0.0" }

clap = { version = "3.0.4", features = ["derive"] }

libc = "0.2.112"
socket2 = "0.4.2"
anyhow = "1.0"

serde = { version = "1.0.133", features = ["derive"] }
serde_derive = "1.0.133"
serde_with = { version = "1.11.0", features = ["macros"] }
serde_json = "1.0.74"
toml = "0.5.8"
humantime = "2.1.0"
humantime-serde = "1.0.1"

addr = { version = "0.15.2" } # features = ["net"] } # create some issue..
regex = "1.5.4"
iprange = "0.6.6"
ipnet = "2.3.1"
chrono = "0.4.19"

rhai = { version = "1.4.0", features = ["unchecked", "sync"] }

# the 0.10 release is more stable than the 0.9 and enable async support.
lettre = "0.10.0-rc.4"
trust-dns-resolver = "0.20.3"

async-trait = "0.1.52"
lazy_static = "1.4"

rustls = { version = "0.20.2", features = ["tls12", "logging"] }
rustls-pemfile = "0.2.1"

tokio = { version = "1.15.0", features = [
    "macros",
    "time",
    "sync",
    "net",
    "io-util",
    "rt-multi-thread",
] }

# inactive since Oct. 2020
users = "0.11"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
fork = "0.1.18"
rand = "0.8.4"

[[bench]]
name = "receiver"
harness = false
