allow-branch = ["main"]
sign-commit = false
sign-tag = false
push-remote = "origin"
release = true
publish = true
verify = true
push = true
push-options = []
dev-version-ext = "alpha.0"
dev-version = false
shared-version = true
consolidate-commits = false
consolidate-pushes = false
pre-release-commit-message = "(cargo-release) version {{version}}"
post-release-commit-message = "(cargo-release) start next development iteration {{next_version}}"
post-release-replacements = []
tag-message = "(cargo-release) {{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
tag = true
enable-features = []
enable-all-features = false
dependent-version = "fix"
