[package]
edition = "2021"

name = "vqueue"
version = "1.1.1"
license = "GPL-3.0-only"

rust-version = "1.58"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vSMTP's queues mananger. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vqueue/"

readme = "../../README.md"
keywords = ["vsmtp"]
categories = ["command-line-utilities"]


[package.metadata.release]
pre-release-replacements = [
    { file = "Cargo.toml", search = "vsmtp-common = \\{ path = \"../vsmtp/vsmtp-common\", default-features = false, version = .*", replace = "vsmtp-common = { path = \"../vsmtp/vsmtp-common\", default-features = false, version = \"{{version}}\" }", prerelease = true },
    { file = "Cargo.toml", search = "vsmtp-config = \\{ path = \"../vsmtp/vsmtp-config\", default-features = false, version = .*", replace = "vsmtp-config = { path = \"../vsmtp/vsmtp-config\", default-features = false, version = \"{{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-common = { path = "../vsmtp/vsmtp-common", default-features = false, version = "1.1.1" }
vsmtp-config = { path = "../vsmtp/vsmtp-config", default-features = false, version = "1.1.1" }

clap = { version = "3.2.8", features = ["derive"] }
itertools = "0.10.3"

[dev-dependencies]
pretty_assertions = "1.2.1"

[features]
default = ["vsmtp-common/gsasl_bindgen"]

# TODO: improve that
[package.metadata.docs.rs]
features = []
all-features = false
no-default-features = true
