[package]
edition = "2021"

name = "vqueue"
version = "1.0.0"
license = "GPL-3.0-only"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vQUEUE : the vSMTP's queues mananger. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

rust-version = "1.58"

[dependencies]
vsmtp-common = { version = "^0.10", path = "../vsmtp/vsmtp-common" }
vsmtp-config = { version = "^0.10", path = "../vsmtp/vsmtp-config" }

clap = { version = "3.1.15", features = ["derive"] }
itertools = "0.10.3"

[dev-dependencies]
pretty_assertions = "1.2.1"
