[package]
edition = "2021"

name = "vsmtp-server"
version = "1.1.0"
license = "GPL-3.0-only"

rust-version = "1.58"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-server/"

readme = "../../../README.md"
keywords = ["vsmtp", "email", "server", "mail-server"]
categories = ["network-programming"]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", version = "1.1.0", default-features = false }
vsmtp-config = { path = "../vsmtp-config", version = "1.1.0", default-features = false }
vsmtp-mail-parser = { path = "../vsmtp-mail-parser", version = "1.1.0", default-features = false }
vsmtp-rule-engine = { path = "../vsmtp-rule-engine", version = "1.1.0", default-features = false }
vsmtp-delivery = { path = "../vsmtp-delivery", version = "1.1.0", default-features = false }

async-trait = "0.1.56"
fastrand = "1.7.0"
thiserror = "1.0.31"

tokio-stream = "0.1.9"
async-stream = "0.3.3"

signal-hook = "0.3.14"

trust-dns-resolver = "0.21.2"
time = { version = "0.3.11", default-features = false, features = [
  "std",
  "formatting",
  "macros",
] }

tokio-rustls = "0.23.4"

[dev-dependencies]
vsmtp-test = { path = "../vsmtp-test" }
pretty_assertions = "1.2.1"

## Benchmark
criterion = { version = "0.3.5", features = ["async_tokio", "html_reports"] }
iai = "0.1.1"
rand = "0.8.5"

lettre = { version = "0.10.0", default-features = false, features = [
  "smtp-transport",
  "builder",
  "tokio1-rustls-tls",
  "tracing",
] }

[features]
default = ["vsmtp-common/gsasl_bindgen"]

# TODO: improve that
[package.metadata.docs.rs]
features = []
all-features = false
no-default-features = true

[[bench]]
name = "receiver2"
harness = false

[[bench]]
name = "iai_receiver"
harness = false
path = "benches/iai/receiver.rs"
