version_requirement = ">=1.0.0, <2.0.0"

[server.logs]
filepath = "/var/log/vsmtp/vsmtp.log"
# see https://docs.rs/log4rs/latest/log4rs/encode/pattern/index.html
# for all available formats.
format = "{d(%Y-%m-%d %H:%M:%S)} {h({l:<5} {I})} ((line:{L:<3})) $ {m}{n}"

[server.logs.level]
default = "warn"
receiver = "info"
rule_engine = "warn"
delivery = "error"
parser = "trace"

[server.smtp.codes]
Greetings = "220 {domain} ESMTP Service ready"

[server.smtp.codes.Help]
code = 214
text = """
This server supports the following commands
HELO EHLO STARTTLS RCPT DATA RSET MAIL QUIT HELP AUTH"""

[server.smtp.codes.TlsRequired]
code = 451
enhanced = "5.7.3"
text = "STARTTLS is required to send mail"

[app.logs]
filepath = "/var/log/vsmtp/app.log"
level = "trace"
format = "{d} - {m}{n}"
archive_count = 100
size_limit = 20_971_520             # 20MB
