version_requirement = "<1.0.0"

[server.logs]
filepath = "/var/log/vsmtp/vsmtp.log"
format = "{d} {l} - "

[server.logs.level]
default = "warn"
receiver = "info"
rule_engine = "warn"
delivery = "error"


[server.smtp.codes]
Help = "214 my custom help message\r\n"
Greetings = "220 {domain} ESMTP Service ready\r\n"


[app.logs]
filepath = "/var/log/vsmtp/app.log"
level = "trace"
format = "{d} - {m}{n}"
