version_requirement = "<1.0.0"

[server]
domain = "testserver.com"
vsmtp_user = "vsmtp"
vsmtp_group = "vsmtp"

[logs.level]
default = "warn"

[rules]
main_filepath = "/etc/vsmtp/rules/main.vsl"

[rules.logs]
file = "/var/log/vsmtp/custom_file.log"
level = "trace"
format = "{d} - {m}{n}"

[[rules.services]]
type = "shell"
name = "echo_hello"
timeout = "500ms"
command = "echo"
args = "hello"

[[rules.services]]
type = "shell"
name = "anti_spam"
timeout = "1500ms"
command = "/usr/bin/anti_spam"
args = "hello"
user = "anti_spam"
group = "anti_spam"

[smtp.timeout_client]
Helo = "100ms"
Data = "200ms"

[smtp.error]
soft_count = 5
hard_count = 10
delay = "1000ms"

[delivery]
spool_dir = "/var/spool/vsmtp"

[delivery.queues]
working = { capacity = 32 }
deliver = { capacity = 32 }
deferred = { retry_max = 10, cron_period = "10s" }

[reply_codes]
Code214 = "214 my custom help message\r\n"
Code220 = "220 {domain} ESMTP Service ready\r\n"
