version_requirement = "<1.0.0"

[server]
domain = "my.fqdn.com"

[server.system]
user = "root"
group = "root"

[server.interfaces]
addr = ["127.0.0.1:25"]
addr_submission = ["127.0.0.1:587"]
addr_submissions = ["127.0.0.1:465"]
