version_requirement = "<1.0.0"

[server]
domain = "my.fqdn.com"

[server.system]
user = "vsmtp"
group = "vsmtp"

[server.interfaces]
addr = ["0.0.0.0:25"]
addr_submission = ["0.0.0.0:587"]
addr_submissions = ["0.0.0.0:465"]
