version_requirement = "<1.0.0"

[server]
domain = "testserver.com"

[server.tls]
security_level = "May"
preempt_cipherlist = false
handshake_timeout = "200ms"
protocol_version = "TLSv1.3"
certificate = "../examples/config/tls/certificate.crt"
private_key = "../examples/config/tls/private_key.key"

[server.virtual.testserver2]
domain = "testserver2.com"
dns = { type = "system" }

[server.virtual.testserver2.tls]
protocol_version = "TLSv1.3"
certificate = "../examples/config/tls/certificate.crt"
private_key = "../examples/config/tls/private_key.key"

[server.virtual.testserver3]
domain = "testserver3.com"
dns = { type = "system" }

[server.virtual.testserver3.tls]
protocol_version = "TLSv1.3"
certificate = "../examples/config/tls/certificate.crt"
private_key = "../examples/config/tls/private_key.key"
