[package]
edition = "2021"

name = "vsmtp-dkim"
version = "1.1.2"
license = "GPL-3.0-only"

rust-version = "1.58"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-dkim/"

readme = "../../../README.md"
keywords = ["vsmtp", "dkim"]
categories = ["data-structures"]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", version = "1.1.0", default-features = false }

thiserror = "1.0.31"
anyhow = "1.0.58"

strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.19.2", default-features = false, features = [
    "macros",
    "time",
    "sync",
    "fs",
    "net",
    "io-util",
    "rt-multi-thread",
] }

base64 = "0.13.0"

sha2 = "0.10.2"
rsa = "0.6.1"
trust-dns-resolver = { version = "0.21.2", default-features = false, features = [
    "system-config",
    "serde-config",
    "tokio-runtime",
] }

# should be optional and under a legacy flag
sha1 = "0.10.1"

convert_case = "0.5.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
vsmtp-mail-parser = { path = "../vsmtp-mail-parser" }

[features]
default = ["vsmtp-common/gsasl_bindgen"]

# TODO: improve that
[package.metadata.docs.rs]
features = []
all-features = false
no-default-features = true
