[package]
edition = "2021"

name = "vsmtp"
version = "0.9.2"
license = "GPLv3"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vSMTP : the next-gen MTA. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

[dependencies]
vsmtp-common = { version = "^0.9", path = "../vsmtp-common" }
vsmtp-server = { version = "^0.9", path = "../vsmtp-server" }
vsmtp-config = { version = "^0.9", path = "../vsmtp-config" }

log = "0.4.14"
log4rs = { version = "1.0.0" }

clap = { version = "3.1.6", features = ["derive"] }

anyhow = "1.0.56"

users = { version = "0.11.0", features = [] }
libc = "0.2.109"

serde_json = "1.0.79"

time = { version = "0.3.7", default-features = false, features = [
    "std",
    "formatting",
    "macros",
] }

lettre = { version = "0.10.0-rc.4", default-features = false, features = [
    "smtp-transport",
    "builder",
    "tokio1-rustls-tls",
    "tracing",
] }

trust-dns-resolver = "0.21.1"

async-trait = "0.1.52"
diff = "0.1.12"

tokio = { version = "1.17.0", features = [
    "macros",
    "time",
    "sync",
    "net",
    "io-util",
    "rt-multi-thread",
] }

[dev-dependencies]
## Stress tests
opentelemetry = { version = "0.17.0", features = ["rt-tokio", "metrics"] }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
lazy_static = "1.4.0"
