[package]
edition = "2021"

name = "vsmtp"
version = "0.9.2"
license = "GPLv3"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vSMTP : the next-gen MTA. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

[dependencies]
vsmtp-common = { version = "^0.9", path = "../vsmtp-common" }
vsmtp-server = { version = "^0.9", path = "../vsmtp-server" }
vsmtp-config = { version = "^0.9", path = "../vsmtp-config" }

log = "0.4.14"
log4rs = { version = "1.0.0" }

clap = { version = "3.1.6", features = ["derive"] }

anyhow = "1.0.56"

users = { version = "0.11.0", features = [] }
libc = "0.2.109"
#
#
# serde = { version = "1.0.136", features = ["derive"] }
# serde_derive = "1.0.136"
# serde_with = { version = "1.12.0", features = ["macros"] }
# humantime-serde = "1.0.1"
#
serde_json = "1.0.79"
# toml = "0.5.8"
#
# humantime = "2.1.0"
#
# addr = { version = "0.15.3" }
# regex = "1.5.4"
# iprange = "0.6.7"
# ipnet = "2.4.0"
time = { version = "0.3.7", default-features = false, features = [
    "std",
    "formatting",
    "macros",
] }
#
# rhai = { version = "1.5.0", features = ["unchecked", "sync", "internals"] }
#
# # the 0.10 release is more stable than the 0.9 and enable async support.
lettre = { version = "0.10.0-rc.4", default-features = false, features = [
    "smtp-transport",
    "builder",
    "tokio1-rustls-tls",
    "tracing",
] }
trust-dns-resolver = "0.21.1"
#
async-trait = "0.1.52"
# enum-iterator = "0.7.0"
diff = "0.1.12"
# fastrand = "1.7.0"
#
# rustls = { version = "0.20.4", features = ["tls12", "logging"] }
# rustls-pemfile = "0.3.0"
#
tokio = { version = "1.17.0", features = [
    "macros",
    "time",
    "sync",
    "net",
    "io-util",
    "rt-multi-thread",
] }
#
# num_cpus = "1.13.1"
# wait-timeout = "0.2.0"
#
# semver = "1.0.6"
#
# [dev-dependencies]
# lazy_static = "1.4.0"
# criterion = { version = "0.3.5", features = ["async_tokio"] }
# rand = "0.8.5"
# webpki-roots = "0.22.2"
# opentelemetry = { version = "0.17.0", features = ["rt-tokio", "metrics"] }
# opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"] }
# pretty_assertions = "1.1.0"

# [[bench]]
# name = "receiver"
# harness = false
