refresh_rate = "30 seconds"

[appenders.default]
kind = "console"

[appenders.default.encoder]
kind = "pattern"
pattern = "{d(%Y-%m-%d %H:%M:%S)} {h({l:<5} {I})} ((line:{L:<3})) $ {m}{n}"

[appenders.requests]
kind = "file"
path = "/tmp/vmta.log"

[appenders.requests.encoder]
pattern = "{d} - {m}{n}"

[root]
level = "info"
appenders = ["default", "requests"]

[loggers.rule_engine]
level = "trace"

[loggers.mail_parser]
level = "warn"

[loggers.mail_receiver]
level = "warn"

[loggers.pipeline]
level = "warn"
