### See vsmtp.default.toml documentation for this file format

version = "0.1.0"
domain = "testserver.com"

[server]
addr = "0.0.0.0:10025"

[log]
file = "./tmp/var/log/vsmtp/vsmtp.log"

[log.level]
default = "trace"
rules = "warn"
receiver = "info"
resolver = "warn"

[rules]
dir = "./config/rules"

[tls]
security_level = "May"
capath = "./config/certs"
preempt_cipherlist = true
handshake_timeout = "100ms"

[[tls.sni_maps]]
domain = "testserver.com"
cert = "{capath}/fullchain.{domain}.pem"
chain = "{capath}/rsa.{domain}.pem"

[smtp]
spool_dir = "./tmp/var/spool/vsmtp"

[smtp.timeout_client]
Helo = "10000ms"
Data = "10000ms"

[smtp.error]
soft_count = 5
hard_count = 10
delay = "5000ms"

[smtp.code]
Code214 = "214 my custom help message\r\n"
