version = "0.1.0"

[log]
## Filepath of logger
file = "./tmp/vsmtp.log"

[log.level]
## Log level of the different part of the program
## Keys are [default/rule_engine/mail_receiver], values in [trace/debug/info/warn/error/off]
default = "warn"
rule_engine = "warn"
mail_receiver = "error"

[paths]
rules_dir = "./config/rules"
spool_dir = "./tmp/spool"
quarantine_dir = "./tmp/quarantine"

[server]
## inet address for the server to listen to
addr = ["0.0.0.0:10025", "0.0.0.0:22", "0.2.3.0:22"]

[tls]
## [none/may/encrypt] => disable/allow/force encryption
security_level = "may"
capath = "./config/certs"
## Use the server's prefered cipherlist instead of the client one
preempt_cipherlist = true
## Maxmimun delay for the tls handshake (milliseconds)
handshake_timeout_ms = 100

sni_maps = [
    { domain = "testserver.com", cert = "{capath}/fullchain.{domain}.pem", chain = "{capath}/rsa.{domain}.pem" },
]

[smtp.timeout_client]
## Delay maximum for the client to the his information
## Keys are [connect/helo/mail/rcpt/data], values in milleseconds (10s if missing)
helo = 5000
data = 500
