[server]
domain = "testserver.com"

[logs]

[rules]
dir = "."

[[rules.services]]
name = "clamscan"
type = "shell"
timeout = "15s"
command = "./service/clamscan.sh"
args = "{mail}"

[delivery]
spool_dir = "/var/spool/vsmtp"
[delivery.queues]
working = { capacity = 32 }
deliver = { capacity = 32 }
deferred = { retry_max = 10, cron_period = "10s" }
