[package]
edition = "2021"

name = "vsmtp-server"
version = "0.9.2"
license = "GPLv3"

authors = ["Team viridIT <https://viridit.com/>"]
description = "vSMTP : the next-gen MTA. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

[dependencies]
vsmtp-common = { version = "^0.9", path = "../vsmtp-common" }
vsmtp-config = { version = "^0.9", path = "../vsmtp-config" }
vsmtp-rule-engine = { version = "^0.9", path = "../vsmtp-rule-engine" }
vsmtp-mail-parser = { version = "^0.9", path = "../vsmtp-mail-parser" }

log = "0.4.14"
anyhow = "1.0.56"

serde_json = "1.0.79"
async-trait = "0.1.52"
fastrand = "1.7.0"

rustls = { version = "0.20.4", features = ["tls12", "logging"] }
rustls-pemfile = "0.3.0"

tokio = { version = "1.17.0", features = [
    "macros",
    "time",
    "sync",
    "net",
    "io-util",
    "rt-multi-thread",
] }

num_cpus = "1.13.1"

[dev-dependencies]
## Benchmark
criterion = { version = "0.3.5", features = ["async_tokio"] }

[[bench]]
name = "receiver"
harness = false
