version_requirement = ">=0.9.0, <1.0.0"

[server]
domain = "example.com"
addr = "0.0.0.0:25"
addr_submission = "0.0.0.0:587"
addr_submissions = "0.0.0.0:465"
thread_count = 10
vsmtp_user = "vsmtp"
vsmtp_group = "vsmtp"

[logs]
file = "/var/log/vsmtp/vsmtp.log"

[logs.level]
default = "warn"

[rules]
dir = "/etc/vsmtp/rules"

[smtps]
security_level = "May"
capath = "/etc/vsmtp/certs"
preempt_cipherlist = true
handshake_timeout = "100ms"
protocol_version = ["TLSv1.3"]

fullchain = "{capath}/certificate.crt"
private_key = "{capath}/private.key"

[smtp]
rcpt_count_max = 25
disable_ehlo = false

[smtp.error]
soft_count = 5
hard_count = 10
delay = "5000ms"

[reply_codes]
Code220 = "220 {domain} ESMTP Service ready\r\n"

[delivery]
spool_dir = "/var/spool/vsmtp"

[delivery.queues]
deferred = { retry_max = 10, cron_period = "10s" }
