name: Fuzz
"on":
  schedule:
    - cron: '0 16 */1 * *' # Every day at 16:00 (4pm)
  push:
    branches:
      - 'ci/fuzz'

jobs:
  check:
    runs-on: self-hosted
    steps:
      # - name: Install gsasl
      #   run: sudo apt-get update && sudo apt-get install -y gsasl libgsasl7-dev
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: '${{ runner.os }}-cargo-registry-${{ hashFiles(''**/Cargo.lock'') }}'
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: '${{ runner.os }}-cargo-index-${{ hashFiles(''**/Cargo.lock'') }}'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check --manifest-path ./fuzz/Cargo.toml
