[server]
domain = "testserver.com"

[logs.level]
default = "warn"

[rules]
dir = "/etc/vsmtp/rules"

[delivery]
spool_dir = "/var/spool/vsmtp"

[delivery.queues]
working = { capacity = 32 }
deliver = { capacity = 32 }
deferred = { retry_max = 10, cron_period = "10s" }
